server:
  port: 8084

spring:
  application:
    name: mall-gateway

  cloud:

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true
      routes:
        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/user/**

