server:
  port: 8083

#management:
    ##  endpoints:
    ##    web:
  ##      exposure:
  ##        include: '*'

spring:
  application:
    name: mall-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

